# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pZOLsN_niIUFWSmxsNGXLCiADrFMgAd
"""

# ==============================
# 1- تثبيت المكتبات
# ==============================
!pip install transformers datasets torch -q

# ==============================
# 2- استيراد المكتبات
# ==============================
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import DataCollatorForLanguageModeling
from transformers import TrainingArguments, Trainer

# ==============================
# 3- تحميل Dataset عربي مباشرة
# ==============================
dataset = load_dataset(
    "wikimedia/wikipedia",
    "20231101.ar",
    split="train[:1%]"
)

# ==============================
# 4- تحميل tokenizer
# ==============================
tokenizer = AutoTokenizer.from_pretrained("aubmindlab/aragpt2-base")
tokenizer.pad_token = tokenizer.eos_token

# ==============================
# 5- تجهيز البيانات
# ==============================
def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

tokenized_dataset = dataset.map(tokenize, batched=True)

# ==============================
# 6- تحميل النموذج
# ==============================
model = AutoModelForCausalLM.from_pretrained("aubmindlab/aragpt2-base")

# ==============================
# 7- Data Collator
# ==============================
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

# ==============================
# 8- إعداد التدريب
# ==============================
training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=2,
    num_train_epochs=1,
    save_steps=500
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator
)

# ==============================
# 9- بدء التدريب
# ==============================
trainer.train()

# ==============================
# 10- تجربة توليد النص
# ==============================
input_text = "الذكاء الاصطناعي"

inputs = tokenizer(input_text, return_tensors="pt")

output = model.generate(
    **inputs,
    max_length=100
)

print(tokenizer.decode(output[0]))

import torch

input_text = "الذكاء الاصطناعي"

inputs = tokenizer(input_text, return_tensors="pt")

# نقل المدخلات لنفس جهاز النموذج (CPU أو GPU)
inputs = {k: v.to(model.device) for k, v in inputs.items()}

output = model.generate(
    **inputs,
    max_length=100
)

print(tokenizer.decode(output[0], skip_special_tokens=True))

prompts = [
"الذكاء الاصطناعي",
"التعليم في العالم العربي",
"الاقتصاد العالمي",
"التكنولوجيا الحديثة"
]

for p in prompts:

    inputs = tokenizer(p, return_tensors="pt")
    inputs = {k: v.to(model.device) for k,v in inputs.items()}

    output = model.generate(
        **inputs,
        max_length=80
    )

    print("Prompt:", p)
    print(tokenizer.decode(output[0], skip_special_tokens=True))
    print("--------------")